coordinatorHost: 192.168.0.189 # MACHINE_IP
coordinatorPort: 4000
localWorkerHost: 192.168.0.189 # MACHINE_IP
workerId: 3
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: follower
    type: MQTT_SOURCE
    configuration:
      url: ws://192.168.0.189:9001 # MACHINE_IP:9001
      topic: follower_gps_fix
