coordinatorHost: 127.0.0.1
coordinatorPort: 4000
localWorkerHost: 127.0.0.1
workerId: 2
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader_inv
    type: MQTT_SOURCE
    configuration:
      url: ws://127.0.0.1:9003
      topic: leader_inv_gps_fix
