services:
  coordinator:
    image: nebulastream/nes-executable-image:latest
    profiles: ["all", "main"]
    command:
     - nesCoordinator
     - --coordinatorHost=${COORDINATOR_IP}
     - --restIp=${COORDINATOR_IP}
     - --restPort=${REST_PORT}
     - --rpcPort=${RPC_PORT}
     - --worker.coordinatorHost=${COORDINATOR_IP}
     - --worker.coordinatorPort=${RPC_PORT}
     - --worker.localWorkerHost=${COORDINATOR_IP}
     - --worker.workerId=${WORKER_ID}
     - --configPath=/config/nebulastream/logical_sources.yml
    network_mode: host
    volumes:
      - ./config/nebulastream:/config/nebulastream
  mosquitto:
    image: eclipse-mosquitto
    profiles: ["all", "main"]
    network_mode: host
    volumes:
      - ./config/mosquitto:/mosquitto/config
  ui:
    image: nebulastream/nes-ui-image:latest
    profiles: ["all", "main"]
    network_mode: host
  subscriber:
    image: python:3-slim
    profiles: ["all", "subscriber"]
    network_mode: host
    volumes:
      - ./scripts:/scripts
      - ./config/subscriber:/config
    command: >
      sh -c "pip install -r /config/requirements && 
             python /scripts/subscriber.py ${COORDINATOR_IP} ${MQTT_PORT}"
  query_1a:
    image: curlimages/curl:latest
    profiles: ["all", "query"]
    network_mode: host
    volumes:
      - ./config/query_1a:/query/
    command: >
      sh /query/run_query_1a.sh
    env_file: .env