coordinatorHost: 0.0.0.0 # IP_KOMPUTERA
coordinatorPort: 4000
localWorkerHost: 0.0.0.0 # IP_KOMPUTERA
workerId: 2
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader
    type: MQTT_SOURCE
    configuration:
      url: ws://0.0.0.0:9001 # IP_KOMPUTERA:9001
      topic: leader_gps_fix
