coordinatorHost: 192.168.0.188 # IP_KOMPUTERA
coordinatorPort: 4000
localWorkerHost: 192.168.0.188 # IP_KOMPUTERA
workerId: 4
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader_inv
    type: MQTT_SOURCE
    configuration:
      url: ws://192.168.0.188:9003 # IP_KOMPUTERA:9003
      topic: leader_inv_gps_fix
