coordinatorHost: 0.0.0.0 # IP_KOMPUTERA
coordinatorPort: 4000
localWorkerHost: 0.0.0.0 # IP_KOMPUTERA
workerId: 3
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: follower
    type: MQTT_SOURCE
    configuration:
      url: ws://0.0.0.0:9002 # IP_KOMPUTERA:9002
      topic: follower_gps_fix
