coordinatorHost: ${NES_COORDINATOR_IP}
coordinatorPort: ${NES_COORDINATOR_RPC_PORT}
localWorkerHost: ${NES_WORKER_LEADER_IP}
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: leader_gps_fix
    type: KAFKA_SOURCE
    configuration:
      brokers: ${NES_WORKER_LEADER_IP}:${KAFKA_PORT}
      topic: gps_fix