services:
  nes_ui:
    image: nebulastream/nes-ui-image:latest
    network_mode: host
  # query_1a:
  # query_1b:
  # subscriber:
  #   build:
  #     context: .
  #     dockerfile: config/subscriber/Dockerfile
  #   profiles: ["all", "subscriber"]
  #   network_mode: host
  #   volumes:
  #     - ./scripts:/scripts
  #   command: ["python", "/scripts/subscriber.py", "${COORDINATOR_IP}", "${MQTT_PORT}"]
  #   env_file: .env