services:
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./config/mosquitto:/mosquitto/config

  nes_ui:
    image: nebulastream/nes-ui-image:latest
    network_mode: host

  geofence_continuous_query:
    build:
      context: .
      dockerfile: config/geofencequery/Dockerfile
    network_mode: host
    volumes:
      - ./data:/data  # Mapujemy folder data, żeby Java widziała plik CSV
    env_file: .env
    # Parametry: 1. Tryb 2. Ścieżka do pliku (wewnątrz kontenera) 3. Nazwa query
    command: ["continuous", "/data/field/1_MONT.csv", "query_1a"]