  ros2_play:
    build:
      context: .
      dockerfile: config/ros2_play/Dockerfile
    profiles: ["all", "ros2_play"]
    network_mode: host
    volumes:
      - ./bags:/bags
    command: ["ros2", "bag", "play", "/bags/${ROBOT_FILE}", "-r", "10.0"]
    env_file: .env
  ros2_kafka:
    build:
      context: .
      dockerfile: config/ros2_kafka/Dockerfile
    profiles: ["all", "ros2_kafka"]
    network_mode: host
    volumes:
      - ./scripts:/scripts
    command: ["python3", "/scripts/ros2_kafka.py", "${WORKER_IP}", "${KAFKA_PORT}"] 
    env_file: .env