services:

  nes_coordinator:
    image: nebulastream/nes-executable-image:latest
    network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesCoordinator
      - --coordinatorHost=${NES_COORDINATOR_IP}
      - --restIp=${NES_COORDINATOR_IP}
      - --restPort=${NES_COORDINATOR_REST_PORT}
      - --rpcPort=${NES_COORDINATOR_RPC_PORT}
      - --worker.coordinatorHost=${NES_COORDINATOR_IP}
      - --worker.coordinatorPort=${NES_COORDINATOR_RPC_PORT}
      - --worker.localWorkerHost=${NES_COORDINATOR_IP}
      - --logLevel=LOG_WARNING
      - --configPath=/config/nes_coordinator_config.yml
    env_file: .env

  mosquitto_leader:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./config/leader:/mosquitto/config

  ros2_mqtt_leader:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    network_mode: host
    volumes:
      - ./scripts:/scripts
    command: [ "python3", "/scripts/ros2_mqtt.py", "${MQTT_IP}", "${MQTT_PORT_LEADER}", "${ROBOT_NAME_LEADER}", "${ROS2_TOPIC_LEADER}", "${MQTT_TOPIC_LEADER}" ]
    env_file: .env

  ros2_play_leader:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    network_mode: host
    volumes:
      - ../ros2_bags:/bags
    command: [ "ros2", "bag", "play", "/bags/${ROBOT_NAME_LEADER}" ]
    env_file: .env

  mosquitto_follower:
    image: eclipse-mosquitto
    # network_mode: host
    ports:
      - 9002:9002
    volumes:
      - ./config/follower:/mosquitto/config

  ros2_mqtt_follower:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    # network_mode: host
    volumes:
      - ./scripts:/scripts
    command: [ "python3", "/scripts/ros2_mqtt.py", "${MQTT_IP}", "${MQTT_PORT_FOLLOWER}", "${ROBOT_NAME_FOLLOWER}", "${ROS2_TOPIC_FOLLOWER}", "${MQTT_TOPIC_FOLLOWER}" ]
    env_file: .env

  ros2_play_follower:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    # network_mode: host
    volumes:
      - ../ros2_bags:/bags
    command: [ "ros2", "bag", "play", "/bags/${ROBOT_NAME_FOLLOWER}" ]
    env_file: .env

  mosquitto_leader_inv:
    image: eclipse-mosquitto
    # network_mode: host
    volumes:
      - ./config/leader_inv:/mosquitto/config

  ros2_mqtt_leader_inv:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    # network_mode: host
    volumes:
      - ./scripts:/scripts
    command: [ "python3", "/scripts/ros2_mqtt.py", "${MQTT_IP}", "${MQTT_PORT_LEADER_INV}", "${ROBOT_NAME_LEADER_INV}", "${ROS2_TOPIC_LEADER_INV}", "${MQTT_TOPIC_LEADER_INV}" ]
    env_file: .env

  ros2_play_leader_inv:
    build:
      context: .
      dockerfile: config/Dockerfile.bridge
    # network_mode: host
    volumes:
      - ../ros2_bags:/bags
    command: [ "ros2", "bag", "play", "/bags/${ROBOT_NAME_LEADER_INV}" ]
    env_file: .env

  nes_worker_leader:
    image: nebulastream/nes-executable-image:latest
    # network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesWorker
      - --configPath=/config/nes_robot_worker_leader_config.yml

  nes_worker_follower:
    image: nebulastream/nes-executable-image:latest
    # network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesWorker
      - --configPath=/config/nes_robot_worker_follower_config.yml

  nes_worker_leader_inv:
    image: nebulastream/nes-executable-image:latest
    # network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesWorker
      - --configPath=/config/nes_robot_worker_leader_inv_config.yml

  mosquitto_results:
    image: eclipse-mosquitto
    # network_mode: host
    ports:
      - 9004:9004
    volumes:
      - ./config/results:/mosquitto/config

  nes_ui:
    image: nebulastream/nes-ui-image:latest
    ports:
      - 9000:9000
    # network_mode: host

  geofence_query:
    build:
      context: .
      dockerfile: config/Dockerfile.geofence
    # network_mode: host
    volumes:
      - ./data:/data
    env_file: .env
    command: [ "/data/field/${FIELD_FILE}", "${GEOFENCE_QUERY}" ]

  subscriber:
    build:
      context: .
      dockerfile: config/Dockerfile.subscriber
    # network_mode: host
    volumes:
      - ./scripts:/scripts
    command: [ "python", "/scripts/subscriber.py", "${QUERY_HOST_IP}", "${MQTT_PORT_RESULTS}", "${QUERY_NAMES}" ]
    env_file: .env

  # humidity_query:
  #   build:
  #     context: .
  #     dockerfile: config/Dockerfile.humidity
  #   network_mode: host
  #   env_file: .env
  #   command: [ "${HUMIDITY_QUERY}" ]
