services:
  nes_worker_leader:
    image: nebulastream/nes-executable-image:latest
    network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesWorker
      - --configPath=/config/nes_worker_leader_config.yml
    env_file: .env

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://${NES_WORKER_LEADER_IP}:${KAFKA_PORT}
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:${KAFKA_CONTROLLER_PORT}
      - ALLOW_PLAINTEXT_LISTENER=yes
    env_file: .env

  # ros2_play:
  #   build:
  #     context: .
  #     dockerfile: config/ros2_play/Dockerfile
  #   profiles: [ "ros" ]
  #   network_mode: host
  #   volumes:
  #     - ../ros2_bags/leader:/bags/leader
  #   command: [ "ros2", "bag", "play", "/bags/leader", "-r", "10.0" ]
  #   env_file: .env

  # ros2_kafka:
  #   build:
  #     context: .
  #     dockerfile: config/ros2_kafka/Dockerfile
  #   profiles: [ "ros" ]
  #   network_mode: host
  #   volumes:
  #     - ./scripts:/scripts
  #   command: [ "python3", "/scripts/ros2_kafka.py", "${NES_WORKER_LEADER_IP}", "${KAFKA_PORT}" ]
  #   env_file: .env
