coordinatorHost: 10.160.46.60
coordinatorPort: 4000
localWorkerHost: 10.160.63.111
workerId: 2

physicalSources:
    - logicalSourceName: gps_position
      physicalSourceName: robot_1
      type: MQTT_SOURCE
      configuration:
          url: ws://mosquitto:9001
          topic: gps_odom