coordinatorHost: 192.168.0.153
coordinatorPort: 4000
localWorkerHost: 192.168.0.163
workerId: 2

physicalSources:
    - logicalSourceName: gps_position
      physicalSourceName: robots_leader_follower
      type: MQTT_SOURCE
      configuration:
          url: ws://192.168.0.163:9001
          topic: gps_fix