coordinatorHost: 192.168.0.153 # 10.160.45.13
coordinatorPort: 4000
localWorkerHost: 192.168.0.163 # 10.160.56.181
workerId: 2
logLevel: LOG_WARNING

physicalSources:
    - logicalSourceName: gps_position
      physicalSourceName: robots_leader_follower
      type: MQTT_SOURCE
      configuration:
          url: ws://192.168.0.163:9001 # ws://10.160.56.181:9001
          topic: gps_fix