services:
  worker:
    image: nebulastream/nes-executable-image:latest
    profiles: ["all", "main"]
    network_mode: host
    volumes:
      - ./config/nebulastream:/config/nebulastream
    command: ["nesWorker", "--configPath=/config/nebulastream/worker_configuration.yml"]
    env_file: .env
  kafka:
    image: bitnami/kafka:latest
    profiles: ["all", "main"]
    network_mode: host
    environment:
<<<<<<< HEAD
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${WORKER_IP}:${KAFKA_PORT}
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:${KAFKA_CONTROLLER_PORT}
=======
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@127.0.0.1:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT},CONTROLLER://:${KAFKA_CONTROLLER_PORT}
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://${WORKER_IP}:${KAFKA_PORT}
>>>>>>> 4658b07ccbd2dcc5fac18370bd7e42f2b2a43e77
    env_file: .env
  ros2_play:
    build:
      context: .
      dockerfile: config/ros2_play/Dockerfile
    profiles: ["all", "ros2_play"]
    network_mode: host
    volumes:
      - ./bags:/bags
    command: ["ros2", "bag", "play", "/bags/${ROBOT_FILE}", "-r", "10.0"]
    env_file: .env
  ros2_kafka:
    build:
      context: .
      dockerfile: config/ros2_kafka/Dockerfile
    profiles: ["all", "ros2_kafka"]
    network_mode: host
    volumes:
      - ./scripts:/scripts
<<<<<<< HEAD
    command: ["python3", "/scripts/ros2_kafka.py", "${WORKER_IP}", "${KAFKA_PORT}"] 
=======
    command: ["python3", "/scripts/ros2_kafka.py", "${WORKER_IP}", "${KAFKA_PORT}"]
>>>>>>> 4658b07ccbd2dcc5fac18370bd7e42f2b2a43e77
    env_file: .env