coordinatorHost: 192.168.0.188
coordinatorPort: 4000
localWorkerHost: 192.168.0.163
workerId: 2
logLevel: LOG_WARNING

physicalSources:
  - logicalSourceName: gps_position
    physicalSourceName: follower
    type: MQTT_SOURCE
    configuration:
      url: ws://192.168.0.163:9001
      topic: follower_gps_fix
