FROM python:3-slim

RUN apt-get update && apt-get install -y \
    libgeos-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

RUN pip install dash plotly shapely paho-mqtt pandas
