services:
  nes_coordinator:
    image: nebulastream/nes-executable-image:latest
    network_mode: host
    volumes:
      - ./config/nebulastream:/config/nes
    command:
      - nesCoordinator
      - --coordinatorHost=${NES_COORDINATOR_IP}
      - --restIp=${NES_COORDINATOR_IP}
      - --restPort=${NES_COORDINATOR_REST_PORT}
      - --rpcPort=${NES_COORDINATOR_RPC_PORT}
      - --worker.coordinatorHost=${NES_COORDINATOR_IP}
      - --worker.coordinatorPort=${NES_COORDINATOR_RPC_PORT}
      - --logLevel=LOG_WARNING
      - --configPath=/config/nes/logical_sources.yml
    env_file: .env
  mosquitto:
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./config/mosquitto:/mosquitto/config
