logicalSources:
    - logicalSourceName: gps_position
      fields:
          - name: timestamp
            type: UINT64
          - name: robot_id
            type: UINT64
          - name: position_x
            type: FLOAT64
          - name: position_y
            type: FLOAT64