services:

  nes_worker:
    image: nebulastream/nes-executable-image:latest
    network_mode: host
    volumes:
      - ./config:/config
    command:
      - nesWorker
      - --coordinatorHost=192.168.0.188
      - --coordinatorPort=4000
      - --localWorkerHost=192.168.0.188
      - --workerId=2
      - --logLevel=LOG_DEBUG
      - --physicalSources.logicalSourceName=temporary
      - --physicalSources.physicalSourceName=kafka
      - --physicalSources.type=KAFKA_SOURCE
      - --physicalSources.brokers=192.168.0.188:40000
      - --physicalSources.topic=kafkee
      - --physicalSources.groupId=testGroup
      - --physicalSources.offset=0
      - --physicalSources.offsetMode=0
      # - --configPath=/config/nes_worker_config.yml
    env_file: .env
